apply plugin: 'checkstyle'
apply plugin: 'pmd'

checkstyle {
  toolVersion = '10.12.4'
  configFile = rootProject.file('config/checkstyle/checkstyle.xml')
  ignoreFailures = false
}

pmd {
  // Required because PMD 7 removed ExcessiveMethodLength
  // and ExcessiveClassLength.
  toolVersion = '6.55.0'

  ruleSets = []
  ruleSetFiles = files(
    rootProject.file('config/pmd/pmd.xml')
  )

  consoleOutput = true
  ignoreFailures = false
}

tasks.withType(org.gradle.api.plugins.quality.Checkstyle).configureEach {
  reports {
    xml.required = true
    html.required = true
  }
}

tasks.withType(org.gradle.api.plugins.quality.Pmd).configureEach {
  reports {
    xml.required = true
    html.required = true
  }
}


[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

sourceSets.main.resources.srcDirs += [rootProject.file('assets').path]

dependencies {
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.github.raeleus.TenPatch:tenpatch:$tenPatchVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
