package ir.hamgit.ahh.PvZ.model.enums;

public enum BehaviorType {
    PRODUCE_SUN,
    INSTANT_SUN_BURST,
    SHOOT_PROJECTILE,
    DELAYED_EXPLOSIVE,
    INSTANT_EXPLOSIVE,
    MELEE_ATTACK,
    PASSIVE_SHIELD,
    MODIFIER_UTILITY,
    MINT_FAMILY_BOOST
}
