package ir.hamgit.ahh.PvZ.model.enums;

public enum BehaviorType {
    PRODUCE_SUN, RAMP_UP_SUN, INSTANT_SUN, DISAPPEAR_AFTER_ACTION,
    SHOOT_FORWARD, SHOOT_ARC, SHOOT_ICE, SHOOT_FIRE, SHOOT_POISON,
    MULTI_SHOT, SHOOT_ADJACENT_LANES, SHOOT_DIAGONAL, SHOOT_BACKWARD,
    SHOOT_FIVE_DIRECTIONS, STACKABLE_HEADS, CHARGED_ATTACK, HOMING_SHOT,
    RANDOM_TARGET, INSTANT_KILL_ZOMBIE, RICOCHET_PROJECTILE, PIERCE_PROJECTILE,
    LIMITED_RANGE, LIMITED_LIFESPAN, FUME_ATTACK, BUTTER_STUN, SPLASH_DAMAGE,
    IGNORE_ARMOR, WARM_AREA, ARM_DELAY, CONTACT_EXPLOSION, AREA_EXPLOSION,
    ADJACENT_SMASH, BOUNCING_PROJECTILES, LANE_EXPLOSION, BOARD_EXPLOSION,
    LEAVE_CRATER, AQUATIC_INSTANT_KILL, CONTACT_FREEZE, MELEE_FRONT_BACK,
    MELEE_AREA, SWALLOW_ZOMBIE, RAMP_UP_DAMAGE, PREVENT_JUMP, REFLECT_DAMAGE,
    BLOCK_ZOMBIES, REDIRECT_ZOMBIE, ATTRACT_ZOMBIES, EXPLODE_ON_DEATH, PROTECTIVE_SHELL,
    SUN_ON_HIT, IGNITE_PROJECTILES, HYPNOTIZE_WHEN_EATEN, COPY_PLANT,
    FREEZE_ALL, WATER_PLATFORM, MELT_ICE, REMOVE_GRAVE, FAMILY_BOOST,
    EXPLODE_ON_PLANT, EXPLODE_AREA, INSTANT_KILL_PLANT, THROW_IMP, REFLECT_PROJECTILES,
    STEAL_SUN, TORCH_BURN, FREEZE_PLANT, LASER_DESTROY, HOOK_PLANT, NEWSPAPER_RAGE,
    SPAWN_IMP_FROM_BARREL, THROW_TOMBSTONE, DYNAMITE_EXPLOSION, TRANSFORM_PLANT_CAT,
    UPGRADE_ZOMBIES, ROW_SHUFFLE, PUSH_OBJECT, FLY_OVER_OBSTACLES, MOVE_REVERSE,
    SWIM_UNDERWATER, HYPNOTIZE, IMMUNE_TO_ICE, IMMUNE_TO_FIRE, IMMUNE_TO_LAWNMOWER,
    STEAL_ARMOR
}
