package ir.hamgit.ahh.PvZ.model.enums;

/** Every plant species defined by the project spec (see plants.csv). */
public enum PlantType {
    PEASHOOTER, SUNFLOWER, CHERRY_BOMB, WALLNUT, POTATO_MINE, SNOW_PEA, CHOMPER, REPEATER,
    PUFF_SHROOM, SUN_SHROOM, FUME_SHROOM, GRAVE_BUSTER, HYPNO_SHROOM, SCAREDY_SHROOM,
    ICE_SHROOM, DOOMSHROOM, LILY_PAD, SQUASH, THREEPEATER, TANGLE_KELP, JALAPENO, SPIKEWEED,
    TORCHWOOD, TALL_NUT, SEA_SHROOM, PLANTERN, CACTUS, BLOVER, SPLIT_PEA, STARFRUIT, PUMPKIN,
    MAGNETSHROOM, CABBAGE_PULT, FLOWER_POT, KERNEL_PULT, COFFEE_BEAN, GARLIC, UMBRELLA_LEAF,
    MARIGOLD, MELON_PULT, GATLING_PEA, TWIN_SUNFLOWER, GLOOM_SHROOM, CATPAIL, WINTER_MELON,
    GOLD_MAGNET, SPIKEROCK, COB_CANNON, IMITATER
}
